### ISSUE TITLE
Is it possible to use .NET Maui or Blazor?

### ISSUE THREAD

**Issue by mehrandvd** [ton-community/wallet-contest#2]
As .NET Maui produces native outputs, I'm wondering if it is possible to use it as we are so hands-on with it.
If you have any performance considerations, I'm certainly sure that .NET Maui result will meet all your requirements.
Here is our experience in creating FxFiles (an open-source file manager) using blazor, targeting android and windows:
https://github.com/functionland/fx-files/

And here is the team:
https://mehrandvd.me/2022/12/18/building-a-ninja-team-for-fxland/

**Comment by Naltox** [comment]
Hi!

Nope, we prefer native languages, any cross platform frameworks are disallowed (expect QT for Desktops)

**Comment by AlexGor-dev** [comment]
It turns out that C# cannot be used for Windows, only C++?

**Comment by tumaygen** [comment]
UQDl0N-ywxgCl0bSm51wqbeiBEPoCQ4hJhXYZuF7XKbfFL9f

**Comment by tumaygen** [comment]
Key competence - cognitive programming of subjective reality: anthropic-individual adjustment of the semantic interpretation of the purpose of existence </mir>

**Comment by tumaygen** [comment]
EQCULL2Fpf5cGiAYvWDGYEah38l_eeMgfKmwjHSHAbNWNuiq
